### ISSUE TITLE
plugin request: setting the root password

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#19]
It seems like setting the root password of the resulting image is a common enough task that it warrants a plugin.

For the record, I currently use the following method:
```yaml
  - shell: |
      # '..VyaTFxP8kT6' is crypt.crypt('raspberry', '..')
      sed -i 's,root:[^:]*,root:..VyaTFxP8kT6,' "${ROOT}/etc/shadow"
    root-fs: root-fs
```

**Comment by larswirzenius** [comment]
I disagree. I don't want to add plugins for all common things, I'd rather people use ansible. But Stuart wants to avoid Ansible, too, to keep image sizes down, so I will ponder on this.

**Comment by stapelberg** [comment]
Thanks for your reply.

I tried using ansible with vmdb2, but found it rather confusing, underdocumented, and, frankly, not very useful in its current state (unless I’m missing something). It seems like one still needs to write and debug shell (the `roles` directory), just with a bunch of additional hoops to jump through. Possibly much of this can be improved by adding more documentation on how things are supposed to work :).

**Comment by llimeht** [comment]
FWIW the prospect of using `sed` on `/etc/shadow` did not appeal and so I currently use:

```yaml
  - shell: |
        chroot "$ROOT" chpasswd < project/root-passwd
    root-fs: root-fs
```
(where `project/root-passwd` is `root:my-plaintext-password`)

To do the same in ansible would be something like

```yaml
- hosts: image
  vars_files:
    - ./project/root-passwd-crypted.yml

  tasks:
    - name: Set the root the root password
      user:
        name: root
        password: "{{root_password_crypted}}"
        update_password: always
```
(where `project/root-passwd-crypted.yml` is `root_password_crypted: "$6$RBPz2HF…"`)

Disclaimer: far from an ansible expert... and this could probably turn into a standard role that vmdb2 distributes rather than being duplicated by each user of vmdb2
