### ISSUE TITLE
mount step with `dirname` unexpectedly removes mountpoint during teardown

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#20]
I’m using the following spec:

```yaml
  - mount: root-part
    fs-tag: root-fs

  - mount: boot-part
    mount-on: root-fs
    dirname: '/boot/firmware'
    fs-tag: boot-fs
```

Unfortunately, `/boot/firmware` is deleted from the root file system during teardown: https://github.com/larswirzenius/vmdb2/blob/36dcf3c9093583935d0279adc85a75806357427c/vmdb/plugins/mount_plugin.py#L84

It seems to me that if `dirname` is set, the directory should not be deleted. Do you agree?
