### ISSUE TITLE
nit: shell and chroot plugin surface are inconsistent

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#25]
```yaml
  - shell: |
      echo 'deb http://deb.debian.org/debian buster main contrib non-free' > "${ROOT?}/etc/apt/sources.list"
    root-fs: root-fs

  - chroot: root-fs
    shell: |
      apt-get clean
      rm -rf /var/lib/apt/lists
```

chroot takes the root-fs as argument, whereas shell takes the shell commands as argument.

While we’re at it, could we rename `shell` to `host`, so that it’s clear which of the two runs where? E.g.:
```yaml
  - host: root-fs
    shell: |
      echo 'deb http://deb.debian.org/debian buster main contrib non-free' > "${ROOT?}/etc/apt/sources.list"

  - chroot: root-fs
    shell: |
      apt-get clean
      rm -rf /var/lib/apt/lists
```
